# Generated by Django 3.1.4 on 2020-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcomic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='cc', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
