# Generated by Django 3.1.4 on 2020-12-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcomic', '0004_auto_20201217_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='Pending', max_length=120),
            preserve_default=False,
        ),
    ]
