# Generated by Django 3.1.4 on 2020-12-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcomic', '0005_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
